
version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 321341
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
    volumes:
      - ./db_backup.sql:/docker-entrypoint-initdb.d/db_backup.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 321341
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_backend
    environment:
      - DATABASE_URL=mysql://root:321341@db:3306/my_database
      - NODE_ENV=development
    ports:
      - "7000:7000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
  
  angular:
    build:
      context: ../client/angular
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ../client/angular:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=1
    command: npm start -- --host 0.0.0.0 --poll=2000

  prisma-studio:
    links:
      - db
    depends_on:
      - db
    container_name: prisma-studio
    ports:
      - '5555:5555'
    build:
      context: docker/prismaStudio
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./prisma:/app/prisma

volumes:
  db_data:
    driver: local
